name: Put data into context.
author: 'MiLaboratories'
description: |
  Put data into context so other jobs can read it later.
  Consider context as key-value store with immutable values.
  Once stored under specific key, the value can not be changed.

  NOTE: for large files use 'cache' GitHub Actions functionality
        as 'context' bases on 'artifacts' and is slow on big files.

inputs:
  key:
    description: |
      The key to use for value storage.
      The value could be retreived from context by this key.
    required: true

  value:
    description: |
      The value to store under key.
    required: true

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/shell@v1
      id: update_key
      env:
        CTX_PATH: ${{ github.action_path }}/ctx
        CTX_KEY: ${{ inputs.key }}
        CTX_VALUE: ${{ inputs.value }}
      with:
        run: |
          mkdir -p "${CTX_PATH}"
          printf "%s" "${CTX_VALUE}" > "${CTX_PATH}/${CTX_KEY}"

    - uses: actions/upload-artifact@v2
      with:
        name: context
        path: ${{ github.action_path }}/ctx/${{ inputs.key }}
