name: Telegram Message
description: |
  Notify User or Channel about build failure

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  build-version:
    description: |
      Build version to display in message
    required: true

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/notify/telegram/send@v1
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: |
          💩 \[${{ inputs.product-name }}] Build failed: ${{ inputs.build-version }}

          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}

          - [View Build on GitHub](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
          - [Source code on GitHub](${{github.server_url}}/${{github.repository}}/tree/${{github.sha}})

          ${{ inputs.additional-info }}
