name: Telegram Message
description: |
  Notify User or Channel about successful dev build

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  build-version:
    description: |
      Build version to display in message
    required: true
  build-category:
    description: |
      Build category: 'dev', 'nigtly', 'whatever' :)
    required: false
    default: 'dev'

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/notify/telegram@v1
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        message: |
          \[${{ inputs.product-name }}] New ${{ inputs.build-category }} build is ready: ${{ inputs.build-version }}

          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}

          [View build on GitHub](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
          [View source code on GitHub](${{github.server_url}}/${{github.repository}}/tree/${{github.sha}})
