name: Telegram Message
description: |
  Notify User or Channel about successful dev build

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  build-version:
    description: |
      Build version to display in message
    required: true
  build-category:
    description: |
      Build category: 'dev', 'nigtly', 'whatever' :)
    required: false
    default: 'dev'

runs:
  using: "composite"

  steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        message: |
          New ${{ inputs.build-category }} build '${{ inputs.build-version }}' in ${{ github.repository }}.

          [View build on GitHub](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
          [View source code on GitHub](${{github.server_url}}/${{github.repository}}/tree/${{github.sha}})
