name: Switch task to new image version
author: 'MiLaboratories'
description: |
  Switch AWS task to new docker image version

inputs:
  task:
    description: |
      Task to update
    required: true

  image:
    description: |
      Image to set for task
    required: true

  run:
    description: |
      Run task after deploy
    required: false

  regions:
    description: |
      List of regions to update task.

      Task will be switched to new image version in listed regions

      You can specify several regions, one per line.
    required: false

  deployment-units:
    description: |
      Deployment units to use for regions detection.

      Task will be switched to new image version in regions that
      have given deployment unit.

      You can specify several units, one per line.
    required: false

runs:
  using: "composite"

  steps:
    - name: Deploy
      uses: milaboratory/github-ci/actions/miaws@v1
      with:
        regions: ${{ inputs.regions }}
        deployment-units: ${{ inputs.deployment-units }}
        args: |-
          appstack
          deploy
          --no-fail-on-empty-changeset
          --task
          ${{ inputs.task }}=${{ inputs.image }}

    - name: Run
      if: inputs.run == 'true'
      uses: milaboratory/github-ci/actions/miaws@v1
      with:
        regions: ${{ inputs.regions }}
        deployment-units: ${{ inputs.deployment-units }}
        args: |-
          appstack
          run
          ${{ inputs.task }}
