name: Run 'gradlew'
author: 'MiLaboratories'
description: |
  Run 'gradlew' script located in gradle project proot

inputs:
  tasks:
    description: |
      Newline-separated list of tasks to run.
    required: true

  properties:
    description: |
      Properties to set for each task run
    required: false
    default: ''

  working-directory:
    description: |
      Path to directory with ./gradlew file
    required: false
    default: ./

  cache-key:
    description: |
      Key to use for gradle build cache
    required: false
    default: 'jdk-common'

runs:
  using: "composite"

  steps:
    - name: Run 'gradlew ${{ inputs.target }}'
      uses: milaboratory/github-ci/actions/java/gradle/cache@v1
      with:
        job-id: ${{ inputs.cache-key }}
        build-root-directory: ${{ inputs.working-directory }}
        properties: ${{ inputs.properties }}
        arguments: ${{ inputs.tasks }}
