name: Telegram Message
description: |
  Notify User or Channel about successful release in repository

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was released
    required: false
    default: ${{ github.repository }}
  release-tag:
    description: |
      Release tag. Optional, defaults to github.sha
    required: true

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/notify/telegram@v1
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        message: |
          🔖 \[${{ inputs.product-name }}] New version was released: ${{ inputs.release-tag }}

          - [View Release on GitHub](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.release-tag }})
          - [Source code on GitHub](${{ github.server_url }}/${{ github.repository }}/tree/${{ inputs.release-tag }})
          - [All releases of ${{ inputs.product-name }}](${{ github.server_url }}/${{ github.repository }}/releases/)
