name: Notify new release created
description: |
  Notify User or Channel about new release

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  version:
    description: |
      Release version number
    required: true
  tag:
    description: |
      Release tag
    required: true

  docker-images:
    description: |
      List of docker images related to build in JSON format
      Empty string is treated as empty JSON list ('[]') for convenience.
    required: false
    default: ''

  maven-packages:
    description: |
      List of maven packages related to build in JSON format
      Empty string is treated as empty JSON list ('[]') for convenience.
    required: false
    default: ''

  links:
    description: |
      URLs to add to notification message. E.g. binary download URL.
    required: false
    default: '[]'

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: safe-ctx
      uses: milaboratory/github-ci/actions/helpers/safe-ctx@v2

    - id: json
      uses: milaboratory/github-ci/actions/shell@v2
      env:
        MAVEN_PACKAGES: ${{ inputs.maven-packages }}
        DOCKER_IMAGES: ${{ inputs.docker-images }}
        LINKS: ${{ inputs.links }}
      with:
        dump-stdout: false
        run: |
          ghwa_set_output "docker-images" "${DOCKER_IMAGES:-[]}"
          ghwa_set_output "maven-packages" "${MAVEN_PACKAGES:-[]}"
          ghwa_set_output "links" "${LINKS:-[]}"

    - uses: milaboratory/github-ci/actions/templates/jinja@v2
      id: message
      with:
        data: |
          { "product": { "name": ${{ toJSON(inputs.product-name) }},
                         "additional_info": ${{ toJSON(inputs.additional-info) }} },

            "release": { "version": ${{ toJSON(inputs.version) }},
                         "tag": ${{ toJSON(inputs.tag) }} },

            "github": ${{ steps.safe-ctx.outputs.github }},

            "docker_images": ${{ fromJSON(steps.json.outputs.data).docker-images }},
            "maven_packages": ${{ fromJSON(steps.json.outputs.data).maven-packages }},
            "links": ${{ fromJSON(steps.json.outputs.data).links }} }

        template: |
          🚀 \[{{ product["name"] }}] New release: [{{ release["version"] }}](
              {{- github["server_url"] }}/{{ github["repository"] }}/releases/tag/{{ release["tag"] -}}
            )

          {%- if docker_images | length > 0 %}
          Docker images:
          {%- for i in docker_images %}
            - ```{{ i }}```
          {%- endfor %}
          {%- endif %}

          {%- if maven_packages | length > 0 %}
          Maven packages:
          {%- for i in maven_packages %}
            - ```{{ i }}```
          {%- endfor %}
          {%- endif %}

          {%- if links | length > 0 %}
          Links:
          {%- for i in links %}
            - ```{{ i }}```
          {%- endfor %}
          {%- endif %}
          \[ [Source code](
            {{- github["server_url"] }}/{{ github["repository"] }}/tree/{{ github["sha"] -}}
          ) | [CI logs](
            {{- github["server_url"] }}/{{ github["repository"] }}/actions/runs/{{ github["run_id"] -}}
          ) ]

          {{ product["additional_info"] }}

    - uses: milaboratory/github-ci/actions/notify/telegram/send@v2
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: ${{ steps.message.outputs.data }}
