name: Telegram Message
description: |
  Notify User or Channel about successful release in repository

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was released
    required: false
    default: ${{ github.repository }}
  release-tag:
    description: |
      Release tag. Optional, defaults to github.sha
    required: true

  docker-images:
    description: |
      List of docker images related to release in JSON format
    required: false
    default: '[]'

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/templates/jinja@v1
      id: message
      with:
        data: |
          { "docker_images": ${{ inputs.docker-images }} }

        template: |
          🔖 \[${{ inputs.product-name }}] New version was released: ${{ inputs.release-tag }}

          - [View Release on GitHub](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.release-tag }})
          - [Source code on GitHub](${{ github.server_url }}/${{ github.repository }}/tree/${{ inputs.release-tag }})
          - [All releases of ${{ inputs.product-name }}](${{ github.server_url }}/${{ github.repository }}/releases/)

          {%- if docker_images | length > 0 %}
          {% for i in docker_images %}
          - {{ i }}
          {% endfor %}
          {% endif %}

          ${{ inputs.additional-info }}

    - uses: milaboratory/github-ci/actions/notify/telegram/send@v1-beta
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: ${{ steps.message.outputs.data }}
