name: Set environment variables for the next steps
author: 'MiLaboratories'
description: |
  Batch setter for environment variables.
  This is just a way to simplify the process when you need to set
  several variables, e.g. passed through inputs or secrets.

inputs:
  json:
    description: |
      JSON map of env variables to set
    required: false
    default: ''

  list:
    description: |
      list of <KEY>=<VALUE> lines with env variables to set
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - name: Set from <json>
      if: inputs.json != ''
      uses: milaboratory/github-ci/actions/shell@v2
      env:
        ENV_TO_SET: ${{ inputs.json }}
      with:
        run: |
          jq -r 'keys[]' <<<"${ENV_TO_SET}" |
              while read -r env_name; do
                env_value="$(
                  jq -r \
                    --arg "key" "${env_name}" \
                    '.[$key]' \
                    <<<"${ENV_TO_SET}"
                )"

                ghwa_set_env "${env_name}" "${env_value}"
              done

    - name: Set from <list>
      if: inputs.list != ''
      uses: milaboratory/github-ci/actions/shell@v2
      env:
        ENV_TO_SET: ${{ inputs.list }}
      with:
        run: |
          echo "${ENV_TO_SET}" |
            while read -r env_line; do
              declare "${env_line}"

              var_name="${env_line%%=*}"
              ghwa_set_env "${var_name}" "${!var_name}"
            done
