name: Publish NodeJS application
author: 'MiLaboratories'
description: |
  Prepare agent for building a Electron project.
  Install Node specific version, download package, create cache e.t.c

inputs:
  node-version:
    description: |
      Node version to use.
      Examples: '16.x', '14.x'

    required: true

  cache-version:
    description: |
      Simple hack, that allows to 'reset' cache for particular job.
      
      Just change the value of this parameter and the next run will
      not find build cache and will have to start from scratch.

    required: false
    default: 'v1'

  is-electron-application:
    description: |
      If 'true' enables cache for an Electron application,
      if 'false', enables cache for a generic NodeJS application.
    required: false
    default: 'false'

  npm-registry-url:
    description: |
      The npm registry url to set up for auth 
      and publication of the node js package.
    required: false
    default: 'https://npm.pkg.github.com'

  npm-registry-scope:
    description: |
      Scope for authenticating against npm registries.
    required: false
    default: ${{ github.repository_owner }}

  github-token:
    description: |
      Repository scope github actions token.
    required: false

runs:
  using: "composite"

  steps:
    - id: context
      uses: milaboratory/github-ci/actions/context@v3

    - name: Prepare env for Node application publishing
      uses: milaboratory/github-ci/actions/node/prepare@v3-beta
      with:
        node-version: ${{ inputs.node-version }}
        cache-version: ${{ inputs.cache-version }}
        is-electron-application: ${{ inputs.is-electron-application }}

    - name: Install node packages with npm
      uses: milaboratory/github-ci/actions/shell@v3
      with:
        run: |
          npm ci

    - name: Patch package version
      uses: milaboratory/github-ci/actions/node/patch-version@v3
      with:
        version: ${{ steps.context.outputs.current-version }}

    - name: Create .npmrc file
      uses: milaboratory/github-ci/actions/shell@v3
      env:
        NPM_REGISTRY_URL: ${{ inputs.npm-registry-url }}
        NPM_REGISTRY_SCOPE: ${{ inputs.npm-registry-scope }}
      with:
        run: |
          echo '//'${NPM_REGISTRY_URL}'/:_authToken=${NPM_AUTH_TOKEN}' > ./.npmrc
          echo "@${NPM_REGISTRY_SCOPE}:registry=${NPM_REGISTRY_URL}" >> ./.npmrc
          echo "always-auth=true" >> ./.npmrc

    - name: Publish NodeJS application
      uses: milaboratory/github-ci/actions/shell@v3
      env:
        NPM_AUTH_TOKEN: ${{ inputs.github-token }}
      with:
        run: |
          npm publish