name: Configure 'miaws' utility
author: 'MiLaboratories'
description: |
  Generate configuration files for 'aws' and 'miaws' utilities

inputs:
  github-token:
    description: |
      Auth token for GitHub container registry (ghcr.io)
      Use {{ secrets.GITHUB_TOKEN }}
    required: true

  aws-key-id:
    description: |
      AWS Access Key ID for API requests
    required: true

  aws-key-secret:
    description: |
      AWS Access Key Secret for API requests
    required: true

  default-region:
    description: |
      Default region for all miaws commands, when no regions are set explicitly
    required: false

runs:
  using: "composite"

  steps:
    # We have to login into 'ghcr.io' manually to be able to pull miaws/cli
    # image on real action run
    - uses: milaboratory/github-ci/actions/docker/login@v1
      with:
        registry: 'ghcr.io'
        user: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    # MiAWS uses official AWS API client, which reads AWS configuration files
    - uses: milaboratory/github-ci/actions/aws/configure@v1
      with:
        key-id: ${{ inputs.aws-key-id }}
        key-secret: ${{ inputs.aws-key-secret }}
        region: ${{ inputs.default-region }}
        append: false
