name: Prepare environment for Node project
author: 'MiLaboratories'
description: |
  Prepare environment: get specific version of Node, download package caches and so on.

inputs:
  node-version:
    description: |
      Node version to use.
      Examples: '16.x', '14.x'
    required: true

  cache-version:
    description: |
      Simple hack, that allows to 'reset' cache for particular job.

      Just change the value of this parameter and the next run will
      not find build cache and will have to start from scratch.

    required: false
    default: 'v1'

  is-electron-application:
    description: |
      If 'true' enables cache for an Electron application,
      if 'false', enables cache for a generic NodeJS application.
    required: false
    default: 'true'

  npm-registry-url:
    description: |
      The npm registry url to set up for auth
      and publication of the node js package.
    required: false
    default: 'https://npm.pkg.github.com'

  npm-registry-scope:
    description: |
      Scope for authenticating against npm registries.
    required: false
    default: ${{ format('{0}{1}', '@', github.repository_owner) }}

runs:
  using: "composite"

  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: ${{ inputs.npm-registry-url }}
        scope: ${{ inputs.npm-registry-scope }}

    - name: Cache NodeJS/Electron libs
      uses: milaboratory/github-ci/actions/node/cache@v3-beta
      with:
        is-electron-application: ${{ inputs.is-electron-application }}
        cache-version: ${{ inputs.cache-version }}
        local-cache: 'on'
