name: 'Build Electron application'
description: |
  Compile and release Electron application.

inputs:
   build-version:
    description: |
       Set version number in 'package.json' file to given value.
    required: false
   build-script-name:
    description: |
      Name of script for application build
    required: true
    default: 'build'
   build-working-directory:
    description: Directory where NPM/Yarn commands should be run
    required: false
    default: '.'
   skip-build:
    description: Whether the action should execute the NPM build script before running 'electron-builder'
    required: false
    default: 'false'
   electron-builder-args:
    description: |
      Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
    required: false
    default: ''
   is-release:
    description: |
      Set If you would like to mark the current version as a release version.
    required: false
    default: 'false'
   github-token:
    description: |
      Copy "github_token" input variable to "GH_TOKEN" env variable (required by 'electron-builder')
    required: true
   mac-sign-cert:
    description: |
      base64-encoded p12 signing certificate file for the macOS
    required: false
   mac-sign-cert-pwd:
    description: |
      password to decrypt the p12 signing certificate for the macOS
    required: false
   mac-notr-api-key:
     description: |
       base64-encoded content of an API key file
     required: false
   mac-notr-api-key-id:
     description: |
       Key ID found on App Store Connect for the API key file
     required: false
   mac-notr-api-key-issuer-id:
     description: |
       Issuer ID found on App Store Connect for the API key file
     required: false
   win-sign-cert:
    description: |
      base64-encoded p12 certificate file for the Windows
    required: false
   win-sign-cert-pwd:
    description: |
      password to decrypt the p12 signing certificate for the Windows
    required: false

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/shell@v4-beta
      if: startsWith(runner.os, 'macOS')
      env:
        APPLE_API_KEY: ${{ inputs.mac-notr-api-key }}
        APPLE_API_KEY_ID: ${{ inputs.mac-notr-api-key-id }}
      with:
        dump-stdout: false
        run: |
          mkdir -p ~/private_keys/
          echo "${APPLE_API_KEY}" | base64 -d > ~/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8

    - uses: milaboratory/github-ci/actions/electron-builder@test-electron-builder
      env:
        VITE_APP_VERSION: ${{ inputs.build-version }}
        APPLE_API_KEY_ID: ${{ inputs.mac-notr-api-key-id }}
        APPLE_API_ISSUER: ${{ inputs.mac-notr_api_key-issuer-id }}
      with:
        build_script_name: ${{ inputs.build-script-name }}
        electron-builder-args: ${{ inputs.electron-builder-args }}
        release: ${{ inputs.is-release }}
        github-token: ${{ inputs.github-token }}
        working-directory: ${{ inputs.build-working-directory }}
        skip-build: ${{ inputs.skip-build }}
        macos-certs: ${{ inputs.mac-sign-cert }}
        macos-certs_password: ${{ inputs.mac-sign-cert-pwd }}
        windows-certs: ${{ inputs.win-sign-cert }}
        windows-certs-password: ${{ inputs.win-sign-cert-pwd }}