name: Build docker image

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths: [ 'docker/**' ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  hooks:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 'hooks'

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/${{ env.IMAGE_NAME }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
