# This workflow tries to automatically generate current app version
# It uses two sources of truth:
#   * GitHub Workflow Action context;
#   * Current git repository state (see 'git describe');
#
# The action does not mutate any files in repository or affect application builds.
# It only sets 'output.version' the user can then pass to another workflows.

name: Autodetect application version

on:
  workflow_call:
    inputs: {}
    outputs:
      version:
        description: 'Automatically detected (generated) version number'
        value: ${{ steps.version_generator.outputs.version }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: milaboratory/github-ci
          path: github-ci

      - name: Generate application version number
        id: version_generator
        run:
          github-ci/scripts/autodetect_version.sh
