# This workflow will prepare given version of Java and use it to build gradle application.
# All gradle dependencies will be cached for next runs.

name: Build Java Application

on:
  workflow_call:
    inputs:
      #
      # Common settings
      #
      app-name:
        description: |
          Application name in human-readable form.
          As it is supposed to be shown in messages
        type: string
        required: false
        default: ${{ github.repository }}
      app-name-slug:
        description: |
          Application name slug (part of release file name)
        type: string
        required: true

      #
      # Version detection control
      #
      version-fetch-depth:
        description: |
          Fetch at least N commits during version detection from tags
        type: string
        required: false
        default: 100
      version-canonize:
        description: |
          Canonize version number to make it always look like regular semver: <major>.<minor>.<bugfix>
        type: boolean
        required: false
        default: true

      #
      # Environment control
      #
      java-version:
        description: |
          Version of JAVA to use for build
        type: string
        required: true

      java-distribution:
        description: |
          Java distribution to use.
          Example: 'temurin', zulu, ...
          See 'https://github.com/actions/setup-java#supported-distributions'
          for complete list of supported distributions
        type: string
        required: false
        default: 'temurin'

      #
      # Build control
      #
      build-project:
        description: |
          Gradle project name to build: gradle :<project>:<command>
        type: string
        required: true

      build-docker:
        description: |
          Build and push docker image (gradle :<project>:dockerBuildImage) for each run.
          Each 'branch' build is stored
        type: boolean
        required: false
        default: true

      build-tar:
        description: |
          Create .tar archive with all jars required for application
          and startup script (gradle :<project>:distTar).
          The archive is saved as artifact with <artifact-retention> TTL.
        type: boolean
        required: false
        default: true

      artifacts-retention:
        description: |
          Time in days to keep build artifacts before removing them
        type: number
        required: false
        default: 7

      build-project-dir:
        description: |
          Path to project root directory
          Defaults to repository root
        type: string
        required: false
        default: './'

      #
      # Release control
      #
      changelog-exclude-types:
        description: |
          Comma-separated list of change types to skip during
          changelog generation for release.

          See 'Conventional Commits' spec for more info:
          https://www.conventionalcommits.org/en/v1.0.0/

          Default: 'doc,chore'
        type: string
        required: false
        default: doc,chore

      #
      # Notifications
      #
      notify-telegram:
        description: |
          Enable Telegram notifications
        required: false
        type: boolean
        default: true

    secrets:
      GRADLE_PROPERTIES:
        description: |
          Create properties file with given contents before starting the build
        required: false

      TELEGRAM_NOTIFICATION_TARGET:
        description: |
          ID of Telegram Channel or User to notify on build results.
        required: false
      TELEGRAM_API_TOKEN:
        description: |
          Telegram Bot API authorization token
        required: false

jobs:
  versions:
    name: Detect versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: versions
        uses: milaboratory/github-ci/actions/detect-version@v1
        with:
          canonize: ${{ inputs.version-canonize }}
          fetch-depth: ${{ inputs.version-fetch-depth }}

    outputs:
      current-version: ${{ steps.versions.outputs.current-version }}
      current-tag: ${{ steps.versions.outputs.current-tag }}
      current-sha: ${{ steps.versions.outputs.current-sha }}

      previous-version: ${{ steps.versions.outputs.previous-version }}
      previous-tag: ${{ steps.versions.outputs.previous-tag }}
      previous-sha: ${{ steps.versions.outputs.previous-sha }}

      latest-version: ${{ steps.versions.outputs.latest-version }}
      latest-tag: ${{ steps.versions.outputs.latest-tag }}
      latest-sha: ${{ steps.versions.outputs.latest-sha }}

      is-branch-head: ${{ steps.versions.outputs.is-branch-head }}

  build:

    name: Build application
    runs-on: ubuntu-latest

    needs:
      - versions

    steps:
      - uses: actions/checkout@v2

      - name: Prepare env for Java application build
        uses: actions/setup-java@v2
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'

      - name: Set gradle.properties
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          printf "%s" "${GRADLE_PROPS}" >> ~/.gradle/gradle.properties

      - name: Read actual project properties
        id: gradle-props
        uses: milaboratory/github-ci/actions/java/gradle/dump-properties@v1
        with:
          project-dir: ${{ inputs.build-project-dir }}
          project-name: ${{ inputs.build-project }}

      - name: Build tar distribution
        if: inputs.build-tar
        working-directory: ${{ inputs.build-project-dir }}
        run: |
          ./gradlew \
            --project-prop "version=${{ needs.versions.outputs.current-version }}" \
            :${{ inputs.build-project }}:distTar

      - name: Save artifact with tar distribution
        if: inputs.build-tar
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.app-name-slug }}-tar
          path: ${{ steps.gradle-props.outputs.buildDir }}/distributions/*.tar
          retention-days: ${{ inputs.artifacts-retention }}

      - name: Build docker image
        if: inputs.build-docker

        working-directory: ${{ inputs.build-project-dir }}
        run: |
          ./gradlew \
            --project-prop "version=${{ needs.versions.outputs.current-version }}" \
            :${{ inputs.build-project }}:dockerBuildImage

      - name: Generate push targets list
        id: push-targets
        if: inputs.build-docker

        uses: milaboratory/github-ci/actions/shell@v1
        env:
          IS_RELEASE: ${{ startsWith( needs.versions.outputs.current-tag, 'v') }}
          IS_LATEST_RELEASE: ${{ needs.versions.outputs.current-tag == needs.versions.outputs.latest-tag }}
          IS_BRANCH_HEAD: ${{ needs.versions.outputs.is-branch-head }}
          BUILD_NAME: ${{ steps.gradle-props.outputs.name }}
          BUILD_VERSION: ${{ needs.versions.outputs.current-version }}
        with:
          run: |
            # Always push '<tag name>:<version>' 'as is'
            echo "${GITHUB_REPOSITORY}/${BUILD_NAME,,}:${BUILD_VERSION,,}"

            if [ "${IS_RELEASE}" = 'true' ]; then
              if [ "${IS_LATEST_RELEASE}" = 'true' ]; then
                # For latest releases also update :latest tag
                echo "${GITHUB_REPOSITORY}/${BUILD_NAME,,}:latest"
              fi
            else
              if [ "${IS_BRANCH_HEAD}" = 'true' ]; then
                # For branch builds update :latest-<branch> tag when we build
                # latest branch commit
                echo "${GITHUB_REPOSITORY}/${BUILD_NAME,,}:latest-${GITHUB_REF_NAME,,}"
              fi
            fi

      - name: Publish docker image to GitHub registry
        id: docker-push
        if: inputs.build-docker

        uses: milaboratory/github-ci/actions/docker/push@v1
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          source: ${{ steps.gradle-props.outputs.name }}:${{ needs.versions.outputs.current-version }}
          targets: ${{ steps.push-targets.outputs.stdout }}

      #
      # Release-only steps
      #
      - name: Create release
        id: create-release
        if: startsWith( needs.versions.outputs.current-tag, 'v')
        uses: milaboratory/github-ci/actions/release/create@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          name: ${{ needs.versions.outputs.current-version }}
          tag: ${{ needs.versions.outputs.current-tag }}

          assets: |
            ${{ steps.gradle-props.outputs.buildDir }}/distributions/*.tar

          changelog-exclude-types: ${{ inputs.changelog-exclude-types }}

    outputs:
      release-id: ${{ steps.create-release.outputs.id }}
      release-url: ${{ steps.create-release.outputs.html_url }}
      docker-tags: ${{ steps.docker-push.outputs.pushed-json }}

  notify-telegram:

    name: Telegram
    runs-on: ubuntu-latest

    if: inputs.notify-telegram

    needs:
      - versions
      - build

    steps:
      - name: Report dev build is ready
        if: needs.build.outputs.release-id == ''
        uses: milaboratory/github-ci/actions/notify/telegram/dev-build-ready@v1
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          product-name: ${{ inputs.app-name }}
          build-version: ${{ needs.versions.outputs.current-version }}
          build-category: dev
          docker-images: ${{ needs.build.outputs.docker-tags }}

      - name: Report release is ready
        if: needs.build.outputs.release-id != ''
        uses: milaboratory/github-ci/actions/notify/telegram/release-ready@v1
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          product-name: ${{ inputs.app-name }}
          release-tag: ${{ needs.versions.outputs.current-tag }}
          docker-images: ${{ needs.build.outputs.docker-tags }}
