# This workflow will prepare given version of Java and use it to build gradle application.
# All gradle dependencies will be cached for next runs.

name: Build Java Application

on:
  workflow_call:
    inputs:
      #
      # Common settings
      #
      app-name:
        description: |
          Application name in human-readable form.
          As it is supposed to be shown in messages
        type: string
        required: false
        default: ${{ github.repository }}
      app-name-slug:
        description: |
          Application name slug (part of release file name)
        type: string
        required: true

      #
      # Version detection control
      #
      version-fetch-depth:
        description: |
          Fetch at least N commits during version detection from tags
        type: string
        required: false
        default: 100
      version-canonize:
        description: |
          Canonize version number to make it always look like regular semver: <major>.<minor>.<bugfix>
        type: boolean
        required: false
        default: true

      #
      # Environment control
      #
      java-version:
        description: |
          Version of JAVA to use for build
        type: string
        required: true

      java-distribution:
        description: |
          Java distribution to use.
          Example: 'temurin', zulu, ...
          See 'https://github.com/actions/setup-java#supported-distributions'
          for complete list of supported distributions
        type: string
        required: false
        default: 'temurin'

      #
      # Build control
      #
      build-project:
        description: |
          Gradle project name to build: gradle :<project>:<command>
        type: string
        required: true

      artifacts-retention:
        description: |
          Time in days to keep build artifacts before removing them
        type: number
        required: false
        default: 7

      build-project-dir:
        description: |
          Path to project root directory
          Defaults to repository root
        type: string
        required: false
        default: './'

      #
      # Release control
      #
      changelog-exclude-types:
        description: |
          Comma-separated list of change types to skip during
          changelog generation for release.

          See 'Conventional Commits' spec for more info:
          https://www.conventionalcommits.org/en/v1.0.0/

          Default: 'doc,chore'
        type: string
        required: false
        default: doc,chore

      #
      # Notifications
      #
      notify-telegram:
        description: |
          Enable Telegram notifications
        required: false
        type: boolean
        default: true

    secrets:
      GRADLE_PROPERTIES:
        description: |
          Create properties file with given contents before starting the build
        required: false

      TELEGRAM_NOTIFICATION_TARGET:
        description: |
          ID of Telegram Channel or User to notify on build results.
        required: false
      TELEGRAM_API_TOKEN:
        description: |
          Telegram Bot API authorization token
        required: false

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1
        with:
          version-fetch-depth: ${{ inputs.version-fetch-depth }}
          version-canonize: ${{ inputs.version-canonize }}

      - id: context
        uses: milaboratory/github-ci/actions/context@v1

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  build:
    name: :build
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/blocks/java/build@v1
        with:
          project: ${{ inputs.build-project }}
          project-dir: ${{ inputs.build-project-dir }}
          tasks: build
          exclude-tasks: test

          properties: |
            mi-ci-stage=build
            ${{ secrets.GRADLE_PROPERTIES }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}

  test:
    name: :test
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/blocks/java/build@v1
        with:
          project: ${{ inputs.build-project }}
          project-dir: ${{ inputs.build-project-dir }}
          tasks: test

          properties: |
            mi-ci-stage=test
            ${{ secrets.GRADLE_PROPERTIES }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}

  distTar:
    name: :distTar
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/blocks/java/build@v1
        with:
          project: ${{ inputs.build-project }}
          project-dir: ${{ inputs.build-project-dir }}
          tasks: distTar
          exclude-tasks: test

          artifact-name: ${{ inputs.app-name-slug }}-tar
          artifact-paths: ./distributions/*.tar
          artifact-retention: ${{ inputs.artifact-retention }}

          properties: |
            mi-ci-stage=dist
            ${{ secrets.GRADLE_PROPERTIES }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}

  distDocker:
    name: :dockerBuildImage
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/blocks/java/build@v1
        with:
          project: ${{ inputs.build-project }}
          project-dir: ${{ inputs.build-project-dir }}
          tasks: dockerBuildImage
          exclude-tasks: test

          properties: |
            mi-ci-stage=dist
            ${{ secrets.GRADLE_PROPERTIES }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}

      - uses: milaboratory/github-ci/blocks/java/publish/docker@v1
        id: docker-push
        with:
          project: ${{ inputs.build-project }}
          project-dir: ${{ inputs.build-project-dir }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      status: ${{ job.status }}
      docker-tags: ${{ steps.docker-push.outputs.pushed-json }}

  notify-build:
    name: Notify build
    runs-on: ubuntu-latest

    if: always() && inputs.notify-telegram

    needs:
      - distDocker

    steps:
      - uses: milaboratory/github-ci/blocks/notify/build@v1
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          build-status: ${{ needs.distDocker.outputs.status }}
          product-name: ${{ inputs.app-name }}
          docker-images: ${{ needs.distDocker.outputs.docker-tags }}

  release:
    name: Release app
    runs-on: ubuntu-latest

    needs:
      - init
      - distDocker

    if: fromJSON(needs.init.outputs.is-release)
    environment: release

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v1

      - uses: actions/download-artifact@v1
        with:
          name: ${{ inputs.app-name-slug }}-tar

      - name: Create release
        if: fromJSON(steps.context.outputs.is-release)
        uses: milaboratory/github-ci/actions/release/create@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          name: ${{ steps.context.outputs.current-version }}
          tag: ${{ steps.context.outputs.current-tag }}

          assets: |
            ${{ inputs.app-name-slug }}-tar/*

          changelog-exclude-types: ${{ inputs.changelog-exclude-types }}
