# This workflow will do a clean prepare of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build Electron Application

on:
  workflow_call:
    inputs:
      #
      # Version detection control
      #
      version-fetch-depth:
        description: |
          Fetch at least N commits during version detection from tags
        type: string
        required: false
        default: 100
      version-canonize:
        description: |
          Canonize version number to make it always look like regular semver: <major>.<minor>.<bugfix>
        type: boolean
        required: false
        default: false

      #
      # Environment control
      #
      node-version:
        description: |
          Node version to use
        type: string
        required: true
      os:
        description: |
          OS to build for.
          Examples: ubuntu-latest, macos-latest, windows-latest

          Check labels of GitHub-hosted runners for more info:
          https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners
        type: string
        required: true

      #
      # Build control
      #
      app-name-slug:
        description: |
          Application name slug (part of release file name)
        type: string
        required: true
      artifacts-retention:
        description: |
          Time in days to keep build artifacts before removing them
        type: number
        required: false
        default: 7
      build-script-name:
        description: |
          Name of script for application build
        type: string
        required: false
        default: 'electron:build'
      vue-project:
        description: |
          This is vue-based project. Use 'vue-cli' toolkit
        type: boolean
        required: false
        default: true

      #
      # Release control
      #
      changelog-exclude-types:
        description: |
          Comma-separated list of change types to skip during
          changelog generation for release.

          See 'Conventional Commits' spec for more info:
          https://www.conventionalcommits.org/en/v1.0.0/

          Default: 'doc,chore'
        type: string
        required: false
        default: doc,chore

jobs:
  detect-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/detect-version@v1
        with:
          canonize: 'true'
          fetch-depth: ${{ inputs.version-fetch-depth }}

    outputs:
      version: ${{ steps.version-detector.outputs.version }}
      tag: ${{ steps.version-detector.outputs.tag }}
      sha: ${{ steps.version-detector.outputs.sha }}

      prev-version: ${{ steps.version-detector.outputs.prev-version }}
      prev-tag: ${{ steps.version-detector.outputs.prev-tag }}
      prev-sha: ${{ steps.version-detector.outputs.prev-sha }}

  build:

    runs-on: ${{ inputs.os }}

    needs:
      - detect-version

    steps:
      - uses: actions/checkout@v2

      - name: Prepare env for Node application build
        uses: milaboratory/github-ci/actions/node/prepare@v1
        with:
          node-version: ${{ inputs.node-version }}
          cache-version: 'v1'

      - name: Install node packages with npm
        run: npm install
        shell: bash

      - name: Patch package version
        uses: milaboratory/github-ci/actions/node/patch-version@v1
        with:
          version: ${{ needs.detect-version.outputs.version }}

      - name: Build application
        run: |
          npm run ${{ inputs.build-script-name }}

      - name: Save artifact with Mac OS X application
        uses: actions/upload-artifact@v2
        if: runner.os == 'macOS'
        with:
          name: ${{ inputs.app-name-slug }}-mac
          path: dist_electron/*.dmg
          retention-days: ${{ inputs.artifacts-retention }}

      - name: Save artifact with Linux application
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: ${{ inputs.app-name-slug }}-linux
          path: dist_electron/*.AppImage
          retention-days: ${{ inputs.artifacts-retention }}

      - name: Create release
        if: startsWith( needs.detect-version.outputs.tag, 'v')
        uses: milaboratory/github-ci/actions/release/create@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          name: ${{ needs.detect-version.outputs.version }}
          tag: ${{ needs.detect-version.outputs.tag }}

          assets: |
            dist_electron/*.dmg,
            dist_electron/*.AppImage

          changelog-exclude-types: ${{ inputs.changelog-exclude-types }}
