# This workflow will do a clean prepare of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build Electron Application

on:
  workflow_call:
    inputs:
      #
      # Common settings
      #
      app-name:
        description: |
          Application name in human-readable form.
          As it is supposed to be shown in texts
        type: string
        required: false
        default: ${{ github.repository }}
      app-name-slug:
        description: |
          Application name slug (part of release file name)
        type: string
        required: true

      #
      # Checkout settings
      #
      git-crypt-unlock:
        description: |
          Perform `git ctypt unlock` after each fresh repository checkout

          NOTE: don't forget to set the following secrets:
                  - GIT_CRYPT_GPG_KEY
                  - GIT_CRYPT_KEY_PASSWORD

        type: boolean
        required: false
        default: false

      checkout-submodules:
        description: |
          'Submodules' mode for 'actions/checkout' action
          '', 'false' - disable submodules support
          'true' - checkout submodules
          'recursive' - checkout submodules recursive
        type: string
        required: false
        default: ''

      #
      # Environment control
      #
      env:
        description: |
          custom environment variables to set for all jobs in workflow
          as JSON-encoded map:
            { "MY_VAR_1": "awesome value",
              "VARIABLE_2": "not so awesome :)" }

          This input's envs are merged with secrets.env
          This input's envs have lower priority compared than secrets.env
        type: string
        required: false
        default: '{}'
      node-version:
        description: |
          Node version to use
        type: string
        required: true
      os:
        description: |
          OS to build for.
          Examples: ubuntu-latest, macos-latest, windows-latest

          Check labels of GitHub-hosted runners for more info:
          https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners
        type: string
        required: true

      #
      # Build control
      #
      artifacts-retention:
        description: |
          Time in days to keep build artifacts before removing them
        type: number
        required: false
        default: 7
      build-script-name:
        description: |
          Name of script for application build
        type: string
        required: false
        default: 'build'
      electron-config-args:
        description: |
          The path to an electron-builder config.
          Defaults to 'electron-builder.yml' (or 'json', or 'json5')
        type: string
        required: false
        default: '.electron-builder.config.js'
      electron-build-args:
        description: |
          List of additional build arguments.
          One argument per line
          '--x64'
          '--arm64'
        type: string
        required: false
        default: ''
      is-vue-project:
        description: |
          This is vue-based project. Use 'vue-cli' toolkit
        type: boolean
        required: false
        default: false
      is-release:
        description: |
          Set If you would like to mark the current version as a release version.
        type: boolean
        required: false
        default: false

      #
      # Test control
      #
      test-unit:
        description: |
          Run unit tests
        type: boolean
        required: false
        default: false
      test-unit-list:
        description: |
         Comma-separated list of unit tests.
         e.g. 'test:e2e', 'test:main' e.t.c
        type: string
        required: false
        default: ''
      test-static:
        description: |
          Run static tests
        type: boolean
        required: false
        default: false
      test-static-list:
        description: |
         Comma-separated list of static tests.
         e.g. 'lint', 'typecheck' e.t.c
        type: string
        required: false
        default: ''

      #
      # Release control
      #
      changelog-exclude-types:
        description: |
          Comma-separated list of change types to skip during
          changelog generation for release.

          See 'Conventional Commits' spec for more info:
          https://www.conventionalcommits.org/en/v1.0.0/

          Default: 'doc,chore'
        type: string
        required: false
        default: doc,chore

      #
      # Notifications
      #
      notify-telegram:
        description: |
          Enable Telegram notifications
        required: false
        type: boolean
        default: true

    secrets:
      env:
        description: |
          custom environment variables to set for all jobs in workflow
          as JSON-encoded map:
            { "MY_VAR_1": "awesome value",
              "VARIABLE_2": "not so awesome :)" }

          This input's envs are merged with inputs.env
          This input's envs have HIGHER priority compared than inputs.env
        required: false

      TELEGRAM_NOTIFICATION_TARGET:
        description: |
          ID of Telegram Channel or User to notify on build results.
        required: false
      TELEGRAM_API_TOKEN:
        description: |
          Telegram Bot API authorization token
        required: false

      GIT_CRYPT_GPG_KEY:
        description: |
          base64-encoded GPG key pair
          (see actions/git/crypt inputs description)
        required: false

      GIT_CRYPT_KEY_PASSWORD:
        description: |
          Password for GPG key
        required: false

      MAC_SIGN_CERT:
        description: |
          base64-encoded p12 certificate file for the macOS
          (more info here https://www.electron.build/code-signing)
        required: false

      MAC_SIGN_CERT_PWD:
        description: |
          password to decrypt the p12 signing certificate for the macOS
        required: false

      WIN_SIGN_CERT:
        description: |
          base64-encoded p12 certificate file for the Windows
          (more info here https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage)
        required: false

      WIN_SIGN_CERT_PWD:
         description: |
          password to decrypt the p12 signing certificate for the Windows
         required: false


jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v2

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  build:
    strategy:
      matrix:
        os: ${{ fromJSON( inputs.os ) }}

    name: Build application
    runs-on: ${{ matrix.os }}

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/actions/env@v2
        with:
          inputs: ${{ inputs.env }}
          secrets: ${{ secrets.env }}

      - uses: actions/checkout@v2
        with:
          submodules: ${{ inputs.checkout-submodules }}

      - uses: milaboratory/github-ci/actions/git/crypt@v2
        if: inputs.git-crypt-unlock
        with:
          gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
          gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

      - uses: milaboratory/github-ci/blocks/node/build@v3-beta
        id: artifact
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          electron-config-args: ${{ inputs.electron-config-args }}
          electron-build-args: ${{ inputs.electron-build-args }}
          is-vue-project: ${{ inputs.is-vue-project }}
          is-release: ${{ needs.init.outputs.is-release }}
          node-version: ${{ inputs.node-version }}
          cache-version: ${{ inputs.cache-version }}

      - name: Save artifact with application
        uses: actions/upload-artifact@v2
        if: fromJSON( steps.artifact.outputs.data ).name != ''
        with:
          name: ${{ fromJSON( steps.artifact.outputs.data ).name }}
          path: ${{ fromJSON( steps.artifact.outputs.data ).path }}
          retention-days: ${{ inputs.artifacts-retention }}

      - name: Upload app to release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-files
          path: ${{ fromJSON( steps.artifact.outputs.data ).path }}
          retention-days: ${{ inputs.artifacts-retention }}

  test-unit:
      strategy:
        fail-fast: false
        matrix:
          os: ${{ fromJSON( inputs.os ) }}
          tests: ${{ fromJSON( inputs.test-unit-list ) }}

      name: :test (unit)
      runs-on: ${{ matrix.os }}

      if: inputs.test-unit
      needs:
        - build

      steps:
        - uses: milaboratory/github-ci/actions/env@v2
          with:
            inputs: ${{ inputs.env }}
            secrets: ${{ secrets.env }}

        - uses: actions/checkout@v2
          with:
            submodules: ${{ inputs.checkout-submodules }}

        - uses: milaboratory/github-ci/actions/git/crypt@v2
          if: inputs.git-crypt-unlock
          with:
            gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
            gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

        - id: test
          uses: milaboratory/github-ci/blocks/node/test@v3-beta
          with:
            test-name: ${{ matrix.tests }}
            node-version: ${{ inputs.node-version }}
            cache-version: ${{ inputs.cache-version }}

      outputs:
        # Even constant outputs become initialized only after job start.
        # All outputs of skipped jobs are always empty.
        started: 'true'


  test-static:
      strategy:
        fail-fast: false
        matrix:
          tests: ${{ fromJSON( inputs.test-static-list ) }}

      name: :test (static)
      runs-on: ubuntu-latest

      if: inputs.test-static
      needs:
        - build

      steps:
        - uses: milaboratory/github-ci/actions/env@v2
          with:
            inputs: ${{ inputs.env }}
            secrets: ${{ secrets.env }}

        - uses: actions/checkout@v2
          with:
            submodules: ${{ inputs.checkout-submodules }}

        - uses: milaboratory/github-ci/actions/git/crypt@v2
          if: inputs.git-crypt-unlock
          with:
            gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
            gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

        - id: test
          uses: milaboratory/github-ci/blocks/node/test@v3-beta
          with:
            test-name: ${{ matrix.tests }}
            node-version: ${{ inputs.node-version }}
            cache-version: ${{ inputs.cache-version }}

      outputs:
        # Even constant outputs become initialized only after job start.
        # All outputs of skipped jobs are always empty.
        started: 'true'

  merge-status:
    name: merge build statuses
    runs-on: ubuntu-latest

    needs:
      - build
      - test-unit
      - test-static

    # This hacky job gets 'success' status only when all build jobs succeed
    # If any of jobs in 'build' matrix fails, <merge-status> gets canceled and
    # has '' (empty string) in <status> output
    steps:
      - shell: bash
        run: 'true'

    outputs:
      status: ${{ job.status }}

  notify-build:
    name: Notify build
    runs-on: ubuntu-latest

    if: always() && inputs.notify-telegram

    needs:
      - merge-status

    steps:
      - uses: milaboratory/github-ci/blocks/notify/build@v2
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          build-status: ${{ needs.merge-status.outputs.status != '' && needs.merge-status.outputs.status || 'failure' }}
          product-name: ${{ inputs.app-name }}

  release:
    name: Create release

    runs-on: ubuntu-latest
    needs:
      - init
      - merge-status

    if:  always()
      && fromJSON(needs.init.outputs.is-release)
      && needs.merge-status.outputs.status == 'success'

    environment: release

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v2

      - uses: actions/download-artifact@v2
        with:
          name: release-files
          path: release-files

      - name: Create release
        id: release
        uses: milaboratory/github-ci/actions/release/create@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          name: ${{ steps.context.outputs.current-version }}
          tag: ${{ steps.context.outputs.current-version-tag }}

          assets: release-files/*

          changelog-exclude-types: ${{ inputs.changelog-exclude-types }}

    outputs:
      release-id: ${{ steps.release.outputs.id }}
      release-url: ${{ steps.release.outputs.html_url }}
