# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build Electron Application

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to use'
        type: string
        required: true
      os:
        description: 'OS to build for'
        type: string
        required: true
      app-name-slug:
        description: 'Application name slug (affects release file name)'
        type: string
        required: true
      npm-build-script:
        description: 'Name of script for application build'
        type: string
        required: false
        default: 'electron:build'

jobs:
  detect-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/autodetect-version@v1

    outputs:
      version: ${{ steps.version-detector.outputs.version }}

  build:

    runs-on: ${{ inputs.os }}

    needs:
      - detect-version

    steps:
      - uses: milaboratory/github-ci/actions/node/electron/build@v1
        with:
          node-version: ${{ inputs.node_version }}
          app-name-slug: ${{ inputs.app-name-slug }}
          npm-build-script: ${{ inputs.npm-build-script }}
          app-version: ${{ needs.detect-version.outputs.version }}
