# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build Electron Application

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node version to use'
        type: string
        required: true
      os:
        description: 'OS to build for'
        type: string
        required: true
      app_name_slug:
        description: 'Application name slug (affects release file name)'
        type: string
        required: true
      npm_build_script:
        description: 'Name of script for application build'
        type: string
        required: false
        default: 'electron:build'

jobs:
  detect-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/autodetect-version@v1

    outputs:
      version: ${{ steps.version-detector.outputs.version }}

  build:

    runs-on: ${{ inputs.os }}

    needs:
      - detect-version

    steps:
      - uses: milaboratory/github-ci/actions/node/electron/build@v1
        with:
          node-version: ${{ inputs.node-version }}
          app_name_slug: ${{ inputs.app_name_slug }}
          npm_build_script: ${{ inputs.npm_build_script }}
          app_version: ${{ needs.detect-version.outputs.version }}
